language: c
python: 2.7

os: linux
dist: trusty
sudo: required

before_install:
#  - if [[ "$INSTALL_ARM_DEPS" == "yes" ]]; then tools/apt-get-install-arm.sh; fi
#  - if [[ "$INSTALL_NUTTX_DEPS" == "yes" ]]; then tools/apt-get-install-nuttx.sh; fi
  - make -f tools/travis/Makefile $PREPARE

install:
  - tools/apt-get-install-deps.sh
  - 

script: tools/build.py
    --buildtype $BUILD_TYPE
    --target-arch "$TARGET_ARCH"
    --target-os "$TARGET_OS"
    --target-board "$TARGET_BOARD"
    $OPTS


env:
  # host build debug and release
  - BUILD_TYPE=debug TARGET_ARCH=x86_64 TARGET_OS=$TRAVIS_OS_NAME
  - BUILD_TYPE=release TARGET_ARCH=x86_64 TARGET_OS=$TRAVIS_OS_NAME

  # cross compilation builds
  - TARGET_ARCH=arm TARGET_OS=linux TARGET_BOARD=rpi2 PREPARE=armhf
  - TARGET_ARCH=arm TARGET_OS=nuttx TARGET_BOARD=stm32f4dis PREPARE=nuttx
  - TARGET_ARCH=arm TARGET_OS=tizen TARGET_BOARD=artik10 PREPARE=tizen

matrix:
  include:
    # this job just lint source code
    - node_js: "6.0"
      install: npm install eslint
      script: 
        - node_modules/.bin/eslint src/js
        - "tools/precommit.py --test=misc"
      env:

branches:
  only:
    - travis_javascript
